
language: node_js

node_js:
  - node
  - 12
  - 10

jobs:
  include:
    - stage: coverage
      node_js: 12
      script:
        - npm run test:cov
        - cat ./coverage/lcov.info | coveralls

sudo: false
